"""export the WRINKLED pial surface to site/data/cortex.js.

the site drew the cortex from an oct5 source space -- about 1,000 dipoles a hemisphere --
which is a set of sampling points, not a surface.  rendered as a mesh it is a smooth blob
with no gyri and no sulci, and it does not look like a brain.

this ships the subject's actual pial surface instead, decimated with a quadric so the folds
survive.  it is the SAME subject the rest of the site already draws (`sample`), so the
result lines up with the scalp, the electrodes and the node cloud that are already there --
fsaverage would have been a different head inside this one's scalp.

per-vertex colour comes from the aparc parcellation the site already uses, so a region
here is the same region it is everywhere else.

    python scripts/export_site_cortex.py --triangles 13000
"""
from __future__ import annotations

import argparse, base64, json, sys
from pathlib import Path
import numpy as np
import mne

ROOT = Path(__file__).resolve().parents[1]
SUBJECTS = ROOT / "data/sources/mne-sample/raw/processed-v6/MNE-sample-data/subjects"
OUT = ROOT / "site" / "data" / "cortex.js"


def b64(a: np.ndarray) -> str:
    return base64.b64encode(np.ascontiguousarray(a).tobytes()).decode("ascii")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--triangles", type=int, default=13000, help="per hemisphere")
    ap.add_argument("--subject", default="sample")
    ap.add_argument("--out", type=Path, default=OUT)
    a = ap.parse_args()

    verts, faces, cols = [], [], []
    off = 0
    for hemi in ("lh", "rh"):
        v, f = mne.read_surface(SUBJECTS / a.subject / "surf" / f"{hemi}.pial")
        v2, f2 = mne.decimate_surface(v, f, n_triangles=a.triangles)
        print(f"{hemi}: {len(v):,} -> {len(v2):,} verts, {len(f):,} -> {len(f2):,} faces")

        # colour by parcellation.  the decimated vertices are NOT a subset of the originals,
        # so each one takes the label of its nearest original vertex rather than an index.
        labels = mne.read_labels_from_annot(a.subject, "aparc", hemi,
                                            subjects_dir=SUBJECTS, verbose=False)
        lab_of = np.full(len(v), -1, dtype=np.int32)
        for li, L in enumerate(labels):
            lab_of[L.vertices] = li
        tree_src = v
        # nearest original vertex per decimated vertex, in chunks to bound memory
        near = np.empty(len(v2), dtype=np.int64)
        CH = 512
        for i in range(0, len(v2), CH):
            d = np.linalg.norm(tree_src[None, :, :] - v2[i:i + CH, None, :], axis=2)
            near[i:i + CH] = d.argmin(1)
        li = lab_of[near]
        rgb = np.zeros((len(v2), 3), dtype=np.uint8)
        for k, L in enumerate(labels):
            c = (np.array(L.color[:3]) * 255).astype(np.uint8)
            rgb[li == k] = c
        rgb[li < 0] = np.array([120, 120, 126], dtype=np.uint8)   # unlabelled: medial wall

        verts.append(v2.astype(np.float32))
        faces.append(f2.astype(np.int64) + off)
        cols.append(rgb)
        off += len(v2)

    V = np.concatenate(verts)
    F = np.concatenate(faces)
    C = np.concatenate(cols)
    if F.max() >= 65536:
        print(f"!! {F.max()+1} vertices exceeds uint16 indices -- lower --triangles", file=sys.stderr)
        return 2

    # positions are in FreeSurfer surface RAS in mm, the same frame the site's node cloud
    # and scalp already use, so they are shipped as-is and only quantised.
    lo, hi = V.min(0), V.max(0)
    scale = (hi - lo).max() / 65534.0
    Q = np.round((V - lo) / scale).astype(np.uint16)

    payload = {
        "subject": a.subject,
        "n_vertices": int(len(V)),
        "n_faces": int(len(F)),
        "origin": [float(x) for x in lo],
        "scale": float(scale),
        "pos": b64(Q),
        "idx": b64(F.astype(np.uint16)),
        "col": b64(C),
    }
    a.out.write_text(
        "/* generated by scripts/export_site_cortex.py -- do not edit by hand.\n"
        f"   the {a.subject} subject's pial surface, quadric-decimated so the gyri survive,\n"
        "   coloured by the aparc parcellation.  same frame as data/graph.js. */\n"
        "window.IBM_CORTEX = " + json.dumps(payload, separators=(",", ":")) + ";\n")
    print(f"{a.out}: {len(V):,} verts, {len(F):,} faces, {a.out.stat().st_size/1e3:.0f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
