"""export the released checkpoints to site/data/releases.js.

§4 of the site lists models by a legible name; the weights behind one are a run
of checkpoints uploaded every `--upload-every` steps by the trainer itself
(ibm/release.py).  this walks the release repo, reads each sidecar for the one
thing the filename does not carry -- the parameter count -- and writes the list
per model, newest step first, so the page can show the progress rather than a
single frozen link.

    python scripts/export_releases.py            # reads HF_TOKEN, or `hf auth token`

the mapping from a checkpoint family to the model it is a checkpoint *of* is
declared in FAMILIES below, because nothing in the filename says it.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

REPO = "jacob-valdez/ibm-1"
OUT = Path(__file__).resolve().parents[1] / "site" / "data" / "releases.js"

# family prefix (everything before .step) -> the model in §4 it belongs to
FAMILIES = {
    "ibm1.m-multi.s300k.e128.k48.dyn-r4.obj-av+meg.vw1": "av_meg_predictor",
    "ibm1.m-multi.s250k.e128.k48.dyn-r4.obj-av+meg.vw1": "av_meg_predictor",
    "ibm1.m-av.s250k.e128.k48.dyn-r4.obj-av.vw1": "av_predictor",
    "ibm1.m-p.s150k.e128.k48.dyn-r4.obj-meg.vw1": "meg_encoder",
    "ibm1.m-ve.s30k.e128.k48.dyn-r4.obj-evoked.vw1": "visual_evoked",
    "ibm1.m-vc.s30k.e128.k48.dyn-r4.obj-contrastive.vw1": "eeg_to_image",
}

STEP_RE = re.compile(r"^checkpoints/(?P<family>.+)\.step(?P<step>\d+)\.git-(?P<sha>\w+)\.pt$")


def token() -> str | None:
    tok = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")
    if tok:
        return tok
    try:  # the cli keeps one, and this script is usually run by whoever trained
        out = subprocess.run(["hf", "auth", "token"], capture_output=True, text=True, timeout=20)
        for line in out.stdout.splitlines():
            line = line.strip()
            if line and not line.lower().startswith("hint"):
                return line
    except (OSError, subprocess.SubprocessError):
        pass
    return None


def get(url: str, tok: str | None) -> bytes:
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {tok}"} if tok else {})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=REPO, help="release repo holding the checkpoints")
    ap.add_argument("--link-repo", default=None, help="repo the site should link to (default: --repo)")
    ap.add_argument("--out", type=Path, default=OUT)
    a = ap.parse_args()
    link_repo = a.link_repo or a.repo
    tok = token()

    listing = json.loads(get(f"https://huggingface.co/api/models/{a.repo}?full=true", tok))
    if "siblings" not in listing:
        print(f"{a.repo}: {listing.get('error', 'no file listing')}", file=sys.stderr)
        return 1

    found: dict[str, list[dict]] = {}
    unclaimed: set[str] = set()
    for sib in listing["siblings"]:
        m = STEP_RE.match(sib["rfilename"])
        if not m:
            continue
        model = FAMILIES.get(m["family"])
        if model is None:
            unclaimed.add(m["family"])
            continue
        found.setdefault(model, []).append(
            {"name": Path(sib["rfilename"]).stem, "path": sib["rfilename"], "step": int(m["step"]), "sha": m["sha"]}
        )
    for fam in sorted(unclaimed):
        print(f"note: no model declared for {fam}", file=sys.stderr)

    # the sidecar carries what the name cannot: how big the thing actually is
    def params(ck: dict) -> None:
        url = f"https://huggingface.co/{a.repo}/resolve/main/" + urllib.parse.quote(ck["path"][:-3] + ".json")
        try:
            side = json.loads(get(url, tok))
        except Exception as e:  # a checkpoint without its sidecar still lists
            print(f"note: no sidecar for {ck['name']}: {e}", file=sys.stderr)
            return
        ck["params"] = side.get("n_params")
        ck["association"] = side.get("n_association_params")

    with ThreadPoolExecutor(max_workers=8) as pool:
        list(pool.map(params, [c for cks in found.values() for c in cks]))

    models = {}
    for model, cks in found.items():
        cks.sort(key=lambda c: c["step"], reverse=True)
        models[model] = [
            {
                "name": c["name"],
                "step": c["step"],
                "params": c.get("params"),
                "url": f"https://huggingface.co/{link_repo}/blob/main/" + urllib.parse.quote(c["path"]),
            }
            for c in cks
        ]

    a.out.write_text(
        "/* generated by scripts/export_releases.py -- the checkpoints released per model,\n"
        f"   newest first, from {a.repo}.  do not edit by hand. */\n"
        "window.IBM_RELEASES = "
        + json.dumps({"repo": link_repo, "models": models}, indent=1, sort_keys=True)
        + ";\n"
    )
    total = sum(len(v) for v in models.values())
    print(f"{a.out}: {total} checkpoints across {len(models)} models")
    for model, cks in sorted(models.items()):
        print(f"  {model}: {len(cks)}, latest step {cks[0]['step']} ({cks[0]['params']} params)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
