"""write docs/RHYTHMS.md and site/data/rhythms.js from ibm/rhythms.py.

    CUDA_VISIBLE_DEVICES="" PYTHONPATH=. .venv/bin/python scripts/export_rhythms.py

One table, three readers: the trainer (`scripts/shape_rhythms.py`), the doc, and the
page.  CLAUDE.md's standing complaint is that changing a constant is not the same as
updating the prose -- `REPO_ID` moved in code while four documents kept pointing at the
old repo.  A generated table cannot drift: edit `ibm/rhythms.py`, run this, commit both.

Neither output is hand-edited.  Both say so at the top.
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ibm.rhythms import (LOOPS, RHYTHMS, STATIONS, check_catalogue, summary)  # noqa: E402

DOC = "docs/RHYTHMS.md"
JS = "site/data/rhythms.js"

HEADER = """# The rhythms this brain is built to have

<!-- GENERATED by scripts/export_rhythms.py from ibm/rhythms.py.  Do not edit by hand:
     edit the catalogue and re-run, or the trainer and the prose will disagree. -->

A brain is not a box that maps inputs to outputs. It is a set of loops, each with an
anatomy, a conduction budget and a band it lives in, and this file is the list of the ones
IBM-1 is being built to have. It is a **specification**: the programme is a construction,
not a search (see `CLAUDE.md`, "Construction, not search"), so these are written down
first and the substrate is shaped toward them.

Three things read the same table, and that is the point of generating this file rather
than writing it:

- `scripts/shape_rhythms.py` turns each entry into a term in the training objective,
  through the differentiable spectral instrument in `ibm/spectral.py`. The spectrum is a
  **pressure during gradient descent**, alongside the anatomical and tractometric ones —
  not something measured afterwards to see where the model happened to land.
- the measurement scripts read the same `measure` spec, so reading a rhythm off real EEG
  and reading it off the model is one code path with two inputs.
- `site/data/rhythms.js`, and through it the resonance section of the site.

## What the evidence column means

| tag | meaning | count |
|---|---|---|
| `measured-here` | fitted in this repo on held-out subjects; the row names the script and the number | {n_measured} |
| `measurable-now` | the corpus is on disk and the instrument exists; nobody has run it | {n_measurable} |
| `literature` | declared from published physiology, no local measurement | {n_literature} |
| `target` | what we intend the substrate to produce; nothing measured at this specificity | {n_target} |

Only **{n_measured}** rows have been through anything in this repository that could have
said no. The rest are declarations, and the column is there so that no reader — including
a future one of us — can mistake the table's completeness for evidence.

`substrate` says what the **model** would need before a row could be scored at all.
`ibm/substrate.py` is a cortical field: {n_expressible} of {n_rhythms} rows are expressible
on it today. A rhythm whose loop runs through the reticular nucleus, the subthalamic
nucleus or the spinal cord is not expressible by a cortical sheet, and scoring its band in
cortex anyway would produce a number that moves for the wrong reason.

## The round-trip bound

A loop cannot oscillate faster than it can go round. With a total round-trip delay `D`
(conduction plus synaptic, summed over the ring), a net-inhibitory loop is bounded by
`f <= 1/(2D)` and a net-excitatory one by `f <= 1/D`.

This is a **ceiling, never a prediction** — most of these frequencies are set by membrane
and synaptic time constants, with the delay far from binding. It is in the table because
it is the one law the table can check against itself, and it earns its place: on the first
run it caught two rhythms filed under the wrong loop (Purkinje synchrony at 200 Hz and
olfactory gamma at 70 Hz were both attached to long loops, when both are produced by local
reciprocal circuits), and one genuine conflict that is now declared as an exception with
its reason (the Piper rhythm). `python ibm/rhythms.py` runs every check.

"""

FOOT = """
## The loops, and their conduction budgets

Round trips are the sum over the ring of declared conduction plus synaptic delay, as an
interval. The ceiling is what the round-trip bound allows.

{loop_table}

## Stations that do not exist yet

The atlas addresses {n_stations} stations, and some of the ones these loops need are
inside a blob or absent altogether. Listed here rather than glossed, because a loop drawn
through a structure the model cannot address is a loop the model cannot have:

{missing}
"""


def fmt_band(r):
    if r.band is None:
        return "—"
    lo, hi = r.band
    unit = "Hz"
    if hi < 0.01:
        return f"{lo:.2e}–{hi:.2e} {unit}"
    if hi < 1:
        return f"{lo:g}–{hi:g} {unit}"
    return f"{lo:g}–{hi:g} {unit}"


def fmt_peak(r):
    if r.peak is None:
        return "—"
    return f"{r.peak:.2e}" if r.peak < 0.01 else f"{r.peak:g}"


def rhythm_table() -> str:
    out = ["| # | rhythm | band | peak (Hz) | loop | states | set by | evidence | substrate |",
           "|---|---|---|---|---|---|---|---|---|"]
    for i, r in enumerate(RHYTHMS, 1):
        states = ", ".join(r.states)
        out.append(f"| {i} | **{r.name}** | {fmt_band(r)} | {fmt_peak(r)} | "
                   f"{LOOPS[r.loop].name} | {states} | {r.set_by} | `{r.evidence}` | "
                   f"`{r.substrate}` |")
    return "\n".join(out)


def mechanism_list() -> str:
    """the same rows again, with the sentence that says what each loop is FOR.

    A table of bands is not a specification of a brain -- the mechanism column is the part
    a reader has to agree with, so it gets room to be read rather than a cell.
    """
    out = []
    for lid, loop in LOOPS.items():
        rs = [r for r in RHYTHMS if r.loop == lid]
        if not rs:
            continue
        lo, hi = loop.delay_ms
        fast, slow = loop.bound_hz()
        out.append(f"### {loop.name}\n")
        out.append(f"{loop.summary}\n")
        out.append(f"Ring: {' → '.join(STATIONS[e.src].name for e in loop.edges)} → "
                   f"{STATIONS[loop.edges[-1].dst].name}. Round trip {lo:g}–{hi:g} ms, net "
                   f"{'inhibitory' if loop.net_sign == '-' else 'excitatory'}, "
                   f"ceiling {slow:.0f}–{fast:.0f} Hz.\n")
        for r in rs:
            line = f"- **{r.name}** ({fmt_band(r)}"
            if r.peak is not None:
                line += f", peak {fmt_peak(r)} Hz"
            line += f", `{r.evidence}`). {r.mechanism}"
            if r.note:
                line += f" *{r.note}*"
            if r.bound_exempt:
                line += f" **Bound exemption:** {r.bound_exempt}"
            if r.refs:
                line += f" [{'; '.join(r.refs)}]"
            out.append(line)
        out.append("")
    return "\n".join(out)


def loop_table() -> str:
    out = ["| loop | ring | round trip | net | ceiling | site tile |", "|---|---|---|---|---|---|"]
    for lid, l in LOOPS.items():
        lo, hi = l.delay_ms
        fast, slow = l.bound_hz()
        ring = " → ".join(STATIONS[e.src].id for e in l.edges)
        out.append(f"| `{lid}` | {ring} | {lo:g}–{hi:g} ms | {l.net_sign} | "
                   f"{slow:.0f}–{fast:.0f} Hz | {'`' + l.site_tile + '`' if l.site_tile else '—'} |")
    return "\n".join(out)


def missing_stations() -> str:
    out = []
    for s in STATIONS.values():
        if s.resolution:
            out.append(f"- **{s.name}** (`{s.id}`) — {s.resolution}")
    return "\n".join(out)


def write_doc() -> str:
    s = summary()
    ev = s["evidence"]
    head = HEADER.format(
        n_measured=ev.get("measured-here", 0), n_measurable=ev.get("measurable-now", 0),
        n_literature=ev.get("literature", 0), n_target=ev.get("target", 0),
        n_expressible=s["substrate"].get("expressible", 0), n_rhythms=s["rhythms"])
    body = (f"## All {s['rhythms']} rhythms\n\n{rhythm_table()}\n\n"
            f"## Loop by loop\n\n{mechanism_list()}")
    foot = FOOT.format(loop_table=loop_table(), n_stations=s["stations"],
                       missing=missing_stations())
    text = head + body + foot
    with open(DOC, "w") as fh:
        fh.write(text)
    return text


def write_js() -> str:
    loops = []
    for lid, l in LOOPS.items():
        rs = [r for r in RHYTHMS if r.loop == lid]
        band = next((r.band for r in rs if r.band), None)
        peak = next((r.peak for r in rs if r.peak), None)
        loops.append({
            "id": lid, "name": l.name, "summary": l.summary, "tile": l.site_tile,
            "ring": [{"station": e.src, "name": STATIONS[e.src].name,
                      "labels": list(STATIONS[e.src].labels), "sign": e.sign,
                      "delay_ms": list(e.delay_ms)} for e in l.edges],
            "round_trip_ms": list(l.delay_ms), "net": l.net_sign,
            "band": list(band) if band else None, "peak": peak,
            "rhythms": [r.id for r in rs],
        })
    rhythms = [{
        "id": r.id, "name": r.name, "loop": r.loop,
        "band": list(r.band) if r.band else None, "peak": r.peak,
        "states": list(r.states), "mechanism": r.mechanism,
        "evidence": r.evidence, "substrate": r.substrate,
    } for r in RHYTHMS]
    payload = {"loops": loops, "rhythms": rhythms}
    text = ("/* GENERATED by scripts/export_rhythms.py from ibm/rhythms.py.  Do not edit.\n"
            "   The site's resonance section draws these loops; the trainer scores the same\n"
            "   table.  `evidence` is carried so a tile can set data-status from it and no\n"
            "   tile can claim a measurement the catalogue does not have. */\n"
            "window.IBM_RHYTHMS = " + json.dumps(payload, indent=1) + ";\n")
    with open(JS, "w") as fh:
        fh.write(text)
    return text


def main() -> int:
    checks = check_catalogue()
    bad = [n for n, ok, _ in checks if not ok]
    if bad:
        print("catalogue FAILED its own checks; nothing written: " + ", ".join(bad))
        return 1
    doc = write_doc()
    js = write_js()
    s = summary()
    print(f"{DOC}: {len(doc.splitlines())} lines, {s['rhythms']} rhythms, {s['loops']} loops")
    print(f"{JS}: {len(js) / 1024:.1f} kB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
